### ISSUE TITLE
hihihih

### ISSUE THREAD

**Issue by Kingerbans** [mk7120/mk7120.github.io#1]
hihihihi

**Comment by mk7120** [comment]
azazaz

**Comment by mk7120** [comment]
Confirm your email address

Your confirmation code is below — enter it in your open browser window and we'll help you get signed in.

N7S-ME4

If you didn’t request this email, there’s nothing to worry about — you can safely ignore it.

**Comment by Kingerbans** [comment]
cac

**Comment by mk7120** [comment]
Welcome to Slack

Here are the details for your new Slack workspace, along with some tips to help you get started.

Workspace name: aaazzz

A

aaazzzgroup.slack.com []

Open Slack [https://aaazzzgroup.slack.com/x-p5496206324374-5488328829495-5503119473970/messages/C05F5EMCE9F]
Tips for getting started

Invite teammates

Slack is made for teams. Invite people [https://aaazzzgroup.slack.com/x-p5496206324374-5488328829495-5503119473970/welcome/invite_members?utm_medium=email&utm_source=confirmation-new-creator] you frequently work or communicate with.

Create channels

Keep work organized in channels [https://aaazzzgroup.slack.com/x-p5496206324374-5488328829495-5503119473970/features/channels?utm_medium=email&utm_source=confirmation-new-creator] — organized spaces for everything related to a project, topic, or team.

Download Slack

For the best experience with Slack, download our apps [https://aaazzzgroup.slack.com/x-p5496206324374-5488328829495-5503119473970/downloads?utm_medium=email&utm_source=confirmation-new-creator&t=T05EL629JB0] for desktop and mobile.

See more tips [https://aaazzzgroup.slack.com/x-p5496206324374-5488328829495-5503119473970/resources/using-slack/top-5-tips-for-getting-started-in-slack?utm_medium=email&utm_source=confirmation-new-creator]

If you have any questions as you’re getting started, drop us a note at ***@***.*** We’re glad you’re here!

**Comment by mk7120** [comment]
Free workspace content older than one year will be deleted

We wanted to let you know about a change in policy [https://slack.com/help/articles/29414264463635] for free workspaces.

What is changing?
Workspaces’ data, including files, messages, and other content that is older than one year will no longer be stored. Free workspaces will continue to have full access to the past 90 days of message history and file storage. This change will not impact workspaces on other plans, such as Slack Pro.

When will this take effect?
This policy will begin taking effect August 26th, 2024. Workspaces will be notified prior to the policy impacting their workspace.

What does this mean for you?

Your workspace, aaazzz , is on a free Slack plan. This workspace has content that is older than one year which will be deleted once the policy takes effect. Moving forward, Slack will not retain messages and files older than one year for a workspace. This policy will impact your workspace starting August 26th, 2024.

To retain access to content older than a year, the workspace needs to be on a paid Slack plan. These plans can be reviewed on our plan page [https://slack.com/pricing]. Free teams will continue to retain access to messages and content sent in the last 90 days.

If your team chooses to upgrade to a paid plan after the policy goes into effect, you will not be able to recover any content that has been deleted under our new policy.

Workspace name: aaazzz
Workspace URL: aaazzzgroup.slack.com
Sign In [https://aaazzzgroup.slack.com/x-t5496206324374-7358489782308/signin]

Questions?Review our FAQs [https://slack.com/help/articles/29414264463635] about this policy change.

**Comment by mk7120** [comment]
New security features for your plan
We are updating our free and paid plans to make your team's workdays more pleasant and productive. All plans now come with enhanced security, and paid plans include powerful AI functionalities.
LEARN MORE [https://slack.com/x-t5496206324374-9132979657424/blog/news/june-2025-pricing-and-packaging-announcement?t=learn_more]
What does this mean for you?

You are a member of a workspace currently on a free Slack plan. The following security features have been added to your Slack plan:

- Limit how long members are signed in to Slack with session duration
- Enforce security policies with built-in native device management

Along with these additional security features, free teams can continue to collaborate seamlessly–communicate with internal and external teams, share clips, capture notes, and manage action items–all in one place.

You can unlock AI features, unlimited message history, group huddles and more by switching to a Slack paid plan. Visit our plans page [https://slack.com/x-t5496206324374-9132979657424/pricing?t=pricing_page] to review or change your plan.

EXPLORE CHANGES [https://slack.com/x-t5496206324374-9132979657424/help/articles/39264531104275?t=explore_changes]

**Comment by mk7120** [comment]
Content older than one year will be deleted starting March 28th, 2026

This is a notice that starting March 28th, 2026, messages and files older than one year will be deleted from your workspace if you remain on the free Slack plan. To retain access to content older than a year, your workspace needs to be on a Slack paid plan. Slack plans can be reviewed on our plans page [https://slack.com/pricing].

If your team chooses to upgrade to a paid plan after the policy goes into effect, you will not be able to recover any content that is deleted under our new policy.

Message and file storage policy for free workspaces

In June 2024, we changed our policy [https://slack.com/help/articles/29414264463635] for free workspace message and file storage. Content in free workspaces—including messages, files, and other content—that is older than a year will be deleted. Free workspaces will continue to have full access to the past 90 days of message history and file storage.

This change does not impact workspaces on other Slack plans, such as Slack Pro.

Workspace name: aaazzz
Workspace URL: aaazzzgroup.slack.com
Sign In [https://aaazzzgroup.slack.com/x-p5496206324374-5488328829495-10388635783890/signin]

Questions? Review our FAQs [https://slack.com/help/articles/29414264463635] about this policy or visit our plans page [http://slack.com/pricing] to switch plans.
